title: Sean Boerhout
description: Student | Arduino-er
cover: images/background.png

twitter: SeanBoe3
facebook: sean.boerhout
github: seanBoe

email: boeseany21@gmail.com

# Google analytics
analytics: G-44DBYLHDVP

url: https://seanboe.github.io
favicon: assets/images/FaviconV3.png

# the sitemap can be found at seanboe.github.io/sitemap.xml
# plugins: [jekyll-sitemap]